### ISSUE TITLE
Pokud selze prehravani, telescreen ceka do konce videa.

### ISSUE THREAD

**Issue by paja-ntk** [techlib/telescreen#7]
Pokud selze prehravani, telescreen ceka dobu, ktera zbyva do konce videa, nepreskoci na dalsi polozku.
Nebylo by spatne, kdyby toto bylo mozne reportovat do indoktrinatoru.

**Comment by mordae** [comment]
Není jak to rozumně řešit.

**Comment by paja-ntk** [comment]
Copak se nedozvis, ze se decoder server ukoncil?

**Comment by mordae** [comment]
1. Není připravený žádný protokol, v rámci kterého bych to hlásil. Není problém, aby vznikl, ale:
2. co by měl Indoktrinátor s touto informací udělat?

Pro konkrétní program je spočítaný harmonogram tak, aby jím mohly zobrazovače procházet zároveň. Nemyslím, že by při chybě mělo dojít k tomu, že se rozjedou.

Jediné, co se dá dělat, je někde zobrazit informaci o tom, že zařízení ohlásilo chybu přehrávání. To asi můžeme udělat. Jen chci vědět, jestli se to děje dostatečně často.
